id: P000320
initial_creation_type: ocr
created_at: 12/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W22115
  title: གསུང་ཐོར་བུ། བསྟན་འཛིན་ནོར་བུ
  author: ''
  volumes:
    ef04b50bdb564323b3da4898367f3505:
      image_group_id: I0877
      title: ''
      volume_number: 1
      total_pages: 514
      base_file: v001.txt
